### ISSUE TITLE
$ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by trafic3** [MarkEdmondson1234/ga-dashboard-demo#3]
Hello

I've got an error when executing the last line: 

>shiny::runApp() 

The error is: $ operator is invalid for atomic vectors.

![Uploading Capture d’écran 2018-04-19 à 13.57.07.png…]()

Alice

**Comment by MarkEdmondson1234** [comment]
Hi Alice, did you follow all the setup steps here? https://github.com/MarkEdmondson1234/ga-dashboard-demo

Can you fix the screenshot so I can see which panel has the error?

Its most likely that the data fetch is not returning any results, so check you have setup correctly and can see data within.  Otherwise you will then have to debug by placing `browser()` lines in the server.R in each function and inspect what was sent in when you run the app.

**Comment by trafic3** [comment]
Mark,

**did you follow all the setup steps here? https://github.com/MarkEdmondson1234/ga-dashboard-demo**

Yes. I've just changed the GA ID and I'm not using any SQL connection.

**Can you fix the screenshot so I can see which panel has the error?**

![capture d ecran 2018-04-19 a 16 43 44 2](https://user-images.githubusercontent.com/33317905/38998908-df4fc178-43f0-11e8-9cfc-8b0379afe952.png)

**Its most likely that the data fetch is not returning any results, so check you have setup correctly and can see data within. Otherwise you will then have to debug by placing browser() lines in the server.R in each function and inspect what was sent in when you run the app.**

The setup seems OK, since I get results from the same GA ID through other R scripts.

Alice

**Comment by trafic3** [comment]
The error is in the ui.r file.

"Error in divTag$attribs : $ operator is invalid for atomic vectors"

**Comment by MarkEdmondson1234** [comment]
Thanks @trafic3 - I found the error which was due to shinydashboard updating how it treated tabPanels.  I updated to the new syntax and it works for me.  Please download from Github again and try it.
